# MOKER framework makecatfile

obj-$(CONFIG_MOKER_TRACING) += trace/trace.o

obj-y += trace/syscalls.o

obj-$(CONFIG_MOKER_SCHED_CBS_POLICY) += sched_cbs/sched.o sched_cbs/cbs_rq.o sched_cbs/syscalls.o
